Update yamladd.yml

diff --git a/.github/workflows/yamladd.yml b/.github/workflows/yamladd.yml
--- a/.github/workflows/yamladd.yml
+++ b/.github/workflows/yamladd.yml
@@ -6,7 +6,10 @@ on:
       OverrideYaml:
         description: 'Provide override yaml to update. Used for appending new configs and overriding existing values.'
         required: true
-        
+      OverwriteYamlFile:
+        description: 'Provide the repo-relative path to a YAML file to overwrite the config.'
+        required: false
+        default: 'override.yml'          
       environment_files:
         description: 'Provide environment specific yaml file name'
         type: choice
@@ -31,7 +34,16 @@ jobs:
         uses: actions/checkout@v6
         with:
           token: ${{ secrets.MYSECRET }}
-
+      
+      - name: Check Inputs
+        run:  |
+          if [ -n "${{ github.event.inputs.OverrideYaml }}" ] && [ -n "${{ github.event.inputs.OverwriteYamlFile }} ]; then
+            echo "Error: Both OverrideYaml and OverwriteYamlFile inputs are provided. Please provide only one."
+            exit 1
+          else
+            echo "Input validation passed. Proceeding with the workflow."
+          fi
+          
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
@@ -43,6 +55,7 @@ jobs:
       - name: Run the patching script
         # Pass OverrideYaml as an env var so multiline newlines are preserved.
         env:
+          OVERWRITE_PATHS: ${{ github.event.inputs.OverwriteYamlFile }}     
           OVERRIDE_YAML: ${{ github.event.inputs.OverrideYaml }}
           ENVIRONMENT_FILES: ${{ github.event.inputs.environment_files }}
           CONFIG_FILE_TYPE: ${{ github.event.inputs.config_file_Type }}
